name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Run PEP8 checks
  pylint:
    uses: ./.github/workflows/pylint.yml

  # Deploy the model if the tests pass
  deploy:
    needs: [pylint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Connect to VPS and deploy the model
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /${{ secrets.VPS_USER }}/HESSIAN
            git checkout .
            git pull
            cd deployment
            bash deploy.sh

  # Run tests
  pytest:
    needs: [deploy]
    uses: ./.github/workflows/pytest.yml
            
            
